import type { CinematicQualityPresetDef } from './types';

/** Quality ladders — each enables the right FX budget for viewport + export. */
export const CINEMATIC_QUALITY_PRESETS: CinematicQualityPresetDef[] = [
  {
    id: 'safe',
    label: 'Safe',
    description: 'Stable Shorts / mobile — minimal post, soft shadows off',
    statePatch: {
      softShadows: false,
      contactShadows: false,
      lightShafts: false,
      volumetricFog: false,
      atmosphericScattering: false,
    },
    patch: {
      qualityMode: 'performance',
      characterQuality: 'standard',
      rtxModeEnabled: false,
      rtxSettings: { aoQuality: 'performance', halfResAo: true, rtxBloomStrength: 0 },
      visualFx: {
        bloomEnabled: false,
        dofEnabled: false,
        ssaoEnabled: false,
        ssaoHalfRes: true,
        smaaEnabled: true,
        godRaysEnabled: false,
        particlesEnabled: false,
        chromaticAberration: 0,
        materialDetailing: false,
        postFxStackEnabled: true,
        floorReflection: 0.55,
        environmentIntensity: 0.85,
        toneExposure: 0.95,
        renderMode: 'mmd_fidelity',
      },
      sceneComposer: {
        effectLevels: {
          bloom: 'off',
          glow: 'off',
          outline: 'low',
          rim: 'off',
          dof: 'off',
          ao: 'off',
          sss: 'off',
          reflection: 'low',
        },
        fogEnabled: false,
        windStrength: 0,
        envBrightness: 0.85,
      },
    },
  },
  {
    id: 'balanced',
    label: 'Balanced',
    description: 'Bloom + AO lite + soft shadows — everyday cinematic',
    statePatch: {
      softShadows: true,
      contactShadows: true,
      lightShafts: false,
      volumetricFog: false,
      atmosphericScattering: true,
    },
    patch: {
      qualityMode: 'balanced',
      characterQuality: 'hd',
      rtxModeEnabled: false,
      rtxSettings: { aoQuality: 'medium', halfResAo: true, rtxBloomStrength: 0.08 },
      visualFx: {
        bloomEnabled: true,
        bloomIntensity: 0.32,
        bloomThreshold: 0.72,
        bloomRadius: 0.32,
        dofEnabled: false,
        ssaoEnabled: true,
        ssaoIntensity: 0.85,
        ssaoHalfRes: true,
        smaaEnabled: true,
        godRaysEnabled: false,
        vignetteEnabled: true,
        vignetteIntensity: 0.18,
        materialDetailing: true,
        materialSmoothing: 0.45,
        postFxStackEnabled: true,
        floorReflection: 0.78,
        environmentIntensity: 0.78,
        toneExposure: 0.92,
        chromaticAberration: 0,
        renderMode: 'asrp',
      },
      sceneComposer: {
        effectLevels: {
          bloom: 'medium',
          glow: 'low',
          outline: 'low',
          rim: 'low',
          dof: 'off',
          ao: 'medium',
          sss: 'low',
          reflection: 'medium',
        },
        fogEnabled: false,
        envBrightness: 0.75,
      },
    },
  },
  {
    id: 'cinematic',
    label: 'Cinematic',
    description: 'DOF, grade, soft shadows, atmosphere — export-ready look',
    statePatch: {
      softShadows: true,
      contactShadows: true,
      lightShafts: true,
      volumetricFog: true,
      atmosphericScattering: true,
    },
    patch: {
      qualityMode: 'quality',
      characterQuality: 'hd',
      rtxModeEnabled: true,
      rtxSettings: {
        aoQuality: 'high',
        halfResAo: false,
        aoIntensity: 2.6,
        rtxBloomStrength: 0.16,
      },
      visualFx: {
        bloomEnabled: true,
        bloomIntensity: 0.4,
        bloomThreshold: 0.58,
        bloomRadius: 0.38,
        dofEnabled: true,
        dofFocusDistance: 0.018,
        dofBokehScale: 2.6,
        ssaoEnabled: true,
        ssaoIntensity: 1.1,
        ssaoHalfRes: false,
        smaaEnabled: true,
        godRaysEnabled: true,
        godRaysDensity: 0.55,
        godRaysSamples: 28,
        vignetteEnabled: true,
        vignetteIntensity: 0.28,
        chromaticAberration: 0.0006,
        colorGrade: 'cinematic',
        materialDetailing: true,
        materialSmoothing: 0.55,
        letterbox239: false,
        postFxStackEnabled: true,
        floorReflection: 0.88,
        environmentIntensity: 0.82,
        toneExposure: 0.88,
        rtxBloomLite: 0.22,
        renderMode: 'asrp',
      },
      sceneComposer: {
        effectLevels: {
          bloom: 'high',
          glow: 'medium',
          outline: 'medium',
          rim: 'medium',
          dof: 'medium',
          ao: 'high',
          sss: 'medium',
          reflection: 'high',
        },
        fogEnabled: true,
        fogDensity: 0.22,
        fogColor: '#c8d4e8',
        envBrightness: 0.78,
        exposure: 0.88,
        contrast: 1.06,
        saturation: 1.04,
      },
    },
  },
  {
    id: 'ultra',
    label: 'Ultra',
    description: 'Max WebGL budget — UHD character, full post, high shadows',
    statePatch: {
      softShadows: true,
      contactShadows: true,
      lightShafts: true,
      volumetricFog: true,
      atmosphericScattering: true,
    },
    patch: {
      qualityMode: 'quality',
      characterQuality: 'uhd4k',
      rtxModeEnabled: true,
      rtxSettings: {
        aoQuality: 'ultra',
        halfResAo: false,
        aoIntensity: 3.1,
        aoRadius: 0.4,
        rtxBloomStrength: 0.22,
      },
      visualFx: {
        bloomEnabled: true,
        bloomIntensity: 0.48,
        bloomThreshold: 0.5,
        bloomRadius: 0.42,
        dofEnabled: true,
        dofFocusDistance: 0.016,
        dofBokehScale: 3.0,
        ssaoEnabled: true,
        ssaoIntensity: 1.25,
        ssaoRadius: 0.36,
        ssaoHalfRes: false,
        smaaEnabled: true,
        godRaysEnabled: true,
        godRaysDensity: 0.7,
        godRaysSamples: 36,
        vignetteEnabled: true,
        vignetteIntensity: 0.32,
        chromaticAberration: 0.001,
        colorGrade: 'cinematic',
        materialDetailing: true,
        materialSmoothing: 0.62,
        letterbox239: true,
        postFxStackEnabled: true,
        floorReflection: 0.94,
        environmentIntensity: 0.9,
        aoIntensity: 4.8,
        toneExposure: 0.86,
        rtxBloomLite: 0.3,
        renderMode: 'asrp',
      },
      sceneComposer: {
        effectLevels: {
          bloom: 'high',
          glow: 'high',
          outline: 'medium',
          rim: 'high',
          dof: 'high',
          ao: 'high',
          sss: 'high',
          reflection: 'high',
        },
        fogEnabled: true,
        fogDensity: 0.28,
        envBrightness: 0.82,
        exposure: 0.86,
        contrast: 1.08,
        saturation: 1.06,
        windStrength: 0.15,
      },
    },
  },
  {
    id: 'rtx_lite',
    label: 'RTX Lite',
    description: 'Silhouette POM + box probes + AO + volumetrics — no real RT',
    statePatch: {
      softShadows: true,
      contactShadows: true,
      lightShafts: true,
      volumetricFog: true,
      atmosphericScattering: true,
    },
    patch: {
      qualityMode: 'quality',
      characterQuality: 'hd',
      rtxModeEnabled: true,
      rtxSettings: {
        aoQuality: 'high',
        halfResAo: true,
        aoIntensity: 2.8,
        aoRadius: 0.38,
        rtxBloomStrength: 0.2,
      },
      visualFx: {
        bloomEnabled: true,
        bloomIntensity: 0.44,
        bloomThreshold: 0.55,
        bloomRadius: 0.4,
        dofEnabled: false,
        ssaoEnabled: true,
        ssaoIntensity: 1.15,
        ssaoHalfRes: true,
        smaaEnabled: true,
        godRaysEnabled: true,
        godRaysDensity: 0.62,
        godRaysSamples: 28,
        vignetteEnabled: true,
        vignetteIntensity: 0.22,
        chromaticAberration: 0.0004,
        colorGrade: 'cinematic',
        materialDetailing: true,
        materialSmoothing: 0.5,
        postFxStackEnabled: true,
        floorReflection: 0.96,
        environmentIntensity: 0.95,
        aoIntensity: 4.4,
        toneExposure: 0.9,
        rtxBloomLite: 0.28,
        renderMode: 'asrp',
      },
      sceneComposer: {
        effectLevels: {
          bloom: 'high',
          glow: 'medium',
          outline: 'low',
          rim: 'medium',
          dof: 'off',
          ao: 'high',
          sss: 'medium',
          reflection: 'high',
        },
        fogEnabled: true,
        fogDensity: 0.18,
        fogColor: '#b8c8e0',
        envBrightness: 0.88,
        exposure: 0.9,
        contrast: 1.05,
        hemisphereIntensity: 1.15,
      },
    },
  },
];

export function getCinematicQualityPreset(id: string): CinematicQualityPresetDef | undefined {
  return CINEMATIC_QUALITY_PRESETS.find((p) => p.id === id);
}
