import type { CinematicRenderStyleDef } from './types';

export const CINEMATIC_RENDER_STYLES: CinematicRenderStyleDef[] = [
  {
    id: 'classic_mmd',
    label: 'Classic MMD',
    description: 'Toon fidelity · light bloom · stage look',
    patch: {
      characterQuality: 'hd',
      visualFx: {
        renderMode: 'mmd_fidelity',
        colorGrade: 'anime',
        scenePreset: 'stage',
        lightPreset: 'anime',
        bloomEnabled: true,
        bloomIntensity: 0.28,
        ssaoEnabled: false,
        materialDetailing: false,
        floorReflection: 0.6,
      },
      sceneComposer: {
        visualStyle: 'anime',
        materialOverride: 'soft_toon',
        effectLevels: { outline: 'high', rim: 'medium', sss: 'off', ao: 'off', bloom: 'low' },
      },
    },
  },
  {
    id: 'anime',
    label: 'Anime',
    description: 'Clean anime grade · soft rim · sparkles',
    patch: {
      characterQuality: 'hd',
      visualFx: {
        renderMode: 'pbr_cinematic',
        colorGrade: 'anime',
        scenePreset: 'studio',
        lightPreset: 'anime',
        bloomEnabled: true,
        bloomIntensity: 0.38,
        ssaoEnabled: true,
        ssaoIntensity: 0.7,
        materialDetailing: true,
        particlesEnabled: true,
        particlePreset: 'sparkles',
        particleIntensity: 0.35,
      },
      sceneComposer: {
        visualStyle: 'anime',
        materialOverride: 'soft_toon',
        effectLevels: { outline: 'medium', rim: 'medium', sss: 'low', ao: 'low', bloom: 'medium' },
      },
    },
  },
  {
    id: 'anime_ultra',
    label: 'Anime Ultra',
    description: 'High rim · SSS · outline · polished grade',
    patch: {
      characterQuality: 'uhd4k',
      rtxModeEnabled: true,
      visualFx: {
        renderMode: 'pbr_cinematic',
        colorGrade: 'anime',
        bloomEnabled: true,
        bloomIntensity: 0.45,
        ssaoEnabled: true,
        materialDetailing: true,
        materialSmoothing: 0.6,
        floorReflection: 0.85,
      },
      sceneComposer: {
        visualStyle: 'soft_anime',
        materialOverride: 'outline',
        effectLevels: {
          outline: 'high',
          rim: 'high',
          sss: 'high',
          ao: 'medium',
          bloom: 'high',
          reflection: 'high',
        },
      },
    },
  },
  {
    id: 'realistic_anime',
    label: 'Realistic Anime',
    description: 'Hybrid Anime PBR · soft face shadows · AO',
    patch: {
      characterQuality: 'hd',
      rtxModeEnabled: true,
      visualFx: {
        renderMode: 'pbr_cinematic',
        colorGrade: 'neutral',
        lightPreset: 'natural',
        bloomEnabled: true,
        bloomIntensity: 0.3,
        ssaoEnabled: true,
        ssaoIntensity: 1.0,
        materialDetailing: true,
        materialSmoothing: 0.5,
        floorReflection: 0.88,
        environmentIntensity: 0.9,
      },
      sceneComposer: {
        visualStyle: 'realistic',
        materialOverride: 'default',
        effectLevels: {
          outline: 'low',
          rim: 'medium',
          sss: 'medium',
          ao: 'high',
          reflection: 'high',
          bloom: 'medium',
        },
      },
    },
  },
  {
    id: 'movie',
    label: 'Movie',
    description: 'Letterbox · cinematic grade · gentle DOF',
    patch: {
      characterQuality: 'hd',
      visualFx: {
        colorGrade: 'cinematic',
        letterbox239: true,
        vignetteEnabled: true,
        vignetteIntensity: 0.35,
        dofEnabled: true,
        dofBokehScale: 2.8,
        bloomEnabled: true,
        bloomIntensity: 0.28,
        chromaticAberration: 0.0008,
      },
      sceneComposer: {
        visualStyle: 'realistic',
        effectLevels: { dof: 'medium', bloom: 'low', ao: 'medium', rim: 'low' },
        contrast: 1.08,
        saturation: 0.98,
      },
    },
  },
  {
    id: 'studio',
    label: 'Studio',
    description: 'Clean key light · high reflection · neutral grade',
    patch: {
      visualFx: {
        scenePreset: 'studio',
        lightPreset: 'natural',
        colorGrade: 'neutral',
        bloomEnabled: false,
        ssaoEnabled: true,
        floorReflection: 0.9,
        environmentIntensity: 0.7,
      },
      sceneComposer: {
        visualStyle: 'studio',
        materialOverride: 'studio',
        skyPreset: 'blue',
        effectLevels: { bloom: 'off', ao: 'high', reflection: 'high', rim: 'low' },
      },
    },
  },
  {
    id: 'netflix',
    label: 'Netflix',
    description: 'Teal-orange grade · contrast · soft bloom',
    patch: {
      visualFx: {
        colorGrade: 'cinematic',
        vignetteEnabled: true,
        vignetteIntensity: 0.25,
        bloomEnabled: true,
        bloomIntensity: 0.26,
        toneExposure: 0.88,
        chromaticAberration: 0.0005,
      },
      sceneComposer: {
        contrast: 1.1,
        saturation: 1.05,
        temperature: 0.08,
        tint: -0.06,
        effectLevels: { bloom: 'low', ao: 'medium', dof: 'low', rim: 'medium' },
      },
    },
  },
  {
    id: 'cinematic',
    label: 'Cinematic',
    description: 'Full atmosphere · god-ray cues · film grade',
    patch: {
      rtxModeEnabled: true,
      visualFx: {
        colorGrade: 'cinematic',
        bloomEnabled: true,
        bloomIntensity: 0.4,
        dofEnabled: true,
        godRaysEnabled: true,
        vignetteEnabled: true,
        vignetteIntensity: 0.3,
        letterbox239: true,
      },
      sceneComposer: {
        visualStyle: 'realistic',
        fogEnabled: true,
        fogDensity: 0.2,
        effectLevels: {
          bloom: 'high',
          dof: 'medium',
          ao: 'high',
          rim: 'medium',
          reflection: 'high',
        },
      },
    },
  },
  {
    id: 'concert',
    label: 'Concert',
    description: 'Stage spot · bloom · particles · neon fill',
    patch: {
      visualFx: {
        scenePreset: 'stage',
        lightPreset: 'concert',
        colorGrade: 'vaporwave',
        bloomEnabled: true,
        bloomIntensity: 0.55,
        particlesEnabled: true,
        particlePreset: 'sparkles',
        particleIntensity: 0.7,
        floorReflection: 0.92,
      },
      sceneComposer: {
        visualStyle: 'cyberpunk',
        effectLevels: { bloom: 'high', glow: 'high', rim: 'high', ao: 'low' },
        windStrength: 0.2,
      },
    },
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'Neon city · cold grade · wet floor',
    patch: {
      visualFx: {
        scenePreset: 'cyber',
        lightPreset: 'neon',
        colorGrade: 'vaporwave',
        bloomEnabled: true,
        bloomIntensity: 0.5,
        wetness: 0.7,
        floorReflection: 0.95,
        vignetteEnabled: true,
        vignetteIntensity: 0.4,
      },
      sceneComposer: {
        visualStyle: 'cyberpunk',
        fogEnabled: true,
        fogDensity: 0.35,
        fogColor: '#102040',
        effectLevels: { bloom: 'high', glow: 'high', reflection: 'high', rim: 'high' },
      },
    },
  },
  {
    id: 'fantasy',
    label: 'Fantasy',
    description: 'Warm magic · soft bloom · dream haze',
    patch: {
      visualFx: {
        colorGrade: 'warm',
        bloomEnabled: true,
        bloomIntensity: 0.42,
        particlesEnabled: true,
        particlePreset: 'fireflies',
        particleIntensity: 0.55,
        scenePreset: 'outdoor',
      },
      sceneComposer: {
        visualStyle: 'fantasy',
        fogEnabled: true,
        fogDensity: 0.24,
        fogColor: '#e8d8f0',
        effectLevels: { bloom: 'high', glow: 'medium', sss: 'medium', rim: 'medium' },
      },
    },
  },
  {
    id: 'dream',
    label: 'Dream',
    description: 'Soft focus · pastel grade · light haze',
    patch: {
      visualFx: {
        colorGrade: 'anime',
        bloomEnabled: true,
        bloomIntensity: 0.5,
        dofEnabled: true,
        dofBokehScale: 3.2,
        vignetteEnabled: true,
        vignetteIntensity: 0.22,
        toneExposure: 1.0,
      },
      sceneComposer: {
        visualStyle: 'soft_anime',
        fogEnabled: true,
        fogDensity: 0.3,
        fogColor: '#f0e8ff',
        saturation: 1.12,
        effectLevels: { bloom: 'high', dof: 'high', glow: 'medium', outline: 'off' },
      },
    },
  },
  {
    id: 'photoreal_anime',
    label: 'Photoreal Anime',
    description: 'PBR skin · env lighting · high AO / reflections',
    patch: {
      characterQuality: 'uhd4k',
      rtxModeEnabled: true,
      rtxSettings: { aoQuality: 'ultra', halfResAo: false, aoIntensity: 3.0 },
      visualFx: {
        renderMode: 'pbr_cinematic',
        colorGrade: 'neutral',
        lightPreset: 'natural',
        bloomEnabled: true,
        bloomIntensity: 0.28,
        ssaoEnabled: true,
        ssaoIntensity: 1.2,
        materialDetailing: true,
        materialSmoothing: 0.55,
        floorReflection: 0.92,
        environmentIntensity: 1.0,
        aoIntensity: 5.0,
      },
      sceneComposer: {
        visualStyle: 'realistic',
        materialOverride: 'default',
        effectLevels: {
          outline: 'off',
          rim: 'low',
          sss: 'high',
          ao: 'high',
          reflection: 'high',
          bloom: 'low',
        },
        envBrightness: 0.92,
      },
    },
  },
];

export function getCinematicRenderStyle(id: string): CinematicRenderStyleDef | undefined {
  return CINEMATIC_RENDER_STYLES.find((s) => s.id === id);
}
