import type { CinematicSunTimeDef } from './types';

/** Advanced sun system — time-of-day looks with atmosphere cues. */
export const CINEMATIC_SUN_TIMES: CinematicSunTimeDef[] = [
  {
    id: 'sunrise',
    label: 'Sunrise',
    azimuth: 85,
    elevation: 12,
    sunColor: '#ffb078',
    colorTempK: 3200,
    intensity: 0.85,
    skyPreset: 'sunset',
    ambientColor: '#ffd0b0',
    ambientIntensity: 0.85,
    patch: {
      visualFx: {
        scenePreset: 'sunset',
        lightPreset: 'natural',
        colorGrade: 'warm',
        bloomEnabled: true,
        bloomIntensity: 0.36,
        toneExposure: 0.9,
        environmentIntensity: 0.75,
      },
      sceneComposer: {
        skyPreset: 'sunset',
        temperature: 0.28,
        tint: 0.05,
        fogEnabled: true,
        fogDensity: 0.2,
        fogColor: '#f0c8a8',
      },
    },
  },
  {
    id: 'noon',
    label: 'Noon',
    azimuth: 135,
    elevation: 58,
    sunColor: '#fff8f0',
    colorTempK: 5600,
    intensity: 1.15,
    skyPreset: 'blue',
    ambientColor: '#d8e4ff',
    ambientIntensity: 1,
    patch: {
      visualFx: {
        scenePreset: 'outdoor',
        lightPreset: 'natural',
        colorGrade: 'neutral',
        toneExposure: 0.95,
        environmentIntensity: 1.0,
      },
      sceneComposer: {
        skyPreset: 'blue',
        temperature: 0,
        tint: 0,
        fogEnabled: false,
        fogDensity: 0.12,
      },
    },
  },
  {
    id: 'sunset',
    label: 'Sunset',
    azimuth: 255,
    elevation: 8,
    sunColor: '#ff8a4a',
    colorTempK: 2800,
    intensity: 0.92,
    skyPreset: 'sunset',
    ambientColor: '#ffc090',
    ambientIntensity: 0.7,
    patch: {
      visualFx: {
        scenePreset: 'sunset',
        lightPreset: 'rim',
        colorGrade: 'warm',
        bloomEnabled: true,
        bloomIntensity: 0.4,
        vignetteEnabled: true,
        vignetteIntensity: 0.3,
        toneExposure: 0.84,
        environmentIntensity: 0.7,
      },
      sceneComposer: {
        skyPreset: 'sunset',
        temperature: 0.35,
        saturation: 1.1,
        fogEnabled: true,
        fogDensity: 0.26,
        fogColor: '#e8a878',
      },
    },
  },
  {
    id: 'golden_hour',
    label: 'Golden Hour',
    azimuth: 250,
    elevation: 18,
    sunColor: '#ffd4a8',
    colorTempK: 3500,
    intensity: 1.0,
    skyPreset: 'sunset',
    ambientColor: '#ffe4c8',
    ambientIntensity: 0.9,
    patch: {
      visualFx: {
        scenePreset: 'sunset',
        lightPreset: 'natural',
        colorGrade: 'warm',
        bloomEnabled: true,
        bloomIntensity: 0.3,
        toneExposure: 0.88,
        environmentIntensity: 0.82,
      },
      sceneComposer: {
        skyPreset: 'sunset',
        temperature: 0.25,
        contrast: 1.05,
        fogEnabled: true,
        fogDensity: 0.16,
        fogColor: '#f0d8b8',
      },
    },
  },
  {
    id: 'blue_hour',
    label: 'Blue Hour',
    azimuth: 270,
    elevation: 4,
    sunColor: '#a8c0ff',
    colorTempK: 9000,
    intensity: 0.55,
    skyPreset: 'night',
    ambientColor: '#8098c8',
    ambientIntensity: 0.95,
    patch: {
      visualFx: {
        scenePreset: 'cyber',
        lightPreset: 'rim',
        colorGrade: 'cold',
        bloomEnabled: true,
        bloomIntensity: 0.28,
        vignetteEnabled: true,
        vignetteIntensity: 0.35,
        toneExposure: 0.78,
        environmentIntensity: 0.65,
      },
      sceneComposer: {
        skyPreset: 'night',
        temperature: -0.25,
        tint: -0.08,
        fogEnabled: true,
        fogDensity: 0.3,
        fogColor: '#6078a8',
      },
    },
  },
  {
    id: 'moonlight',
    label: 'Moonlight',
    azimuth: 200,
    elevation: 35,
    sunColor: '#c8d8ff',
    colorTempK: 10000,
    intensity: 0.4,
    skyPreset: 'night',
    ambientColor: '#6070a0',
    ambientIntensity: 0.7,
    patch: {
      visualFx: {
        scenePreset: 'nightclub',
        lightPreset: 'rim',
        colorGrade: 'noir',
        bloomEnabled: true,
        bloomIntensity: 0.22,
        vignetteEnabled: true,
        vignetteIntensity: 0.4,
        toneExposure: 0.72,
        environmentIntensity: 0.5,
      },
      sceneComposer: {
        skyPreset: 'night',
        temperature: -0.35,
        saturation: 0.92,
        fogEnabled: true,
        fogDensity: 0.22,
        fogColor: '#304060',
        exposure: 0.75,
      },
    },
  },
];

export function getCinematicSunTime(id: string): CinematicSunTimeDef | undefined {
  return CINEMATIC_SUN_TIMES.find((s) => s.id === id);
}
