import type { SmartMetadataLocale } from './types';

const LOCALE_STORAGE_KEY = 'as_app_locale';

export const SMART_METADATA_LOCALES: SmartMetadataLocale[] = [
  'en',
  'ja',
  'ru',
  'es',
  'fr',
  'de',
  'pt',
];

export const LOCALE_LABELS: Record<SmartMetadataLocale, string> = {
  en: 'English',
  ja: '日本語',
  ru: 'Русский',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  pt: 'Português',
};

export function isSmartMetadataLocale(v: string): v is SmartMetadataLocale {
  return SMART_METADATA_LOCALES.includes(v as SmartMetadataLocale);
}

/** Browser / saved preference — default for metadata generation. */
export function detectAppLocale(): SmartMetadataLocale {
  if (typeof localStorage !== 'undefined') {
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
    if (stored && isSmartMetadataLocale(stored)) return stored;
  }
  if (typeof navigator !== 'undefined') {
    const code = navigator.language.slice(0, 2).toLowerCase();
    if (isSmartMetadataLocale(code)) return code;
  }
  return 'en';
}

export function persistAppLocale(locale: SmartMetadataLocale): void {
  try {
    localStorage.setItem(LOCALE_STORAGE_KEY, locale);
  } catch {
    /* quota / private mode */
  }
}

export interface MetadataUiStrings {
  panelTitle: string;
  platform: string;
  language: string;
  titles: string;
  description: string;
  hashtags: string;
  keywords: string;
  copyTitle: string;
  copyDescription: string;
  copyHashtags: string;
  copyAll: string;
  regenerate: string;
  copied: string;
  copyFailed: string;
  createdWith: string;
  character: string;
  motion: string;
  stage: string;
  visualStyle: string;
  shaderPack: string;
  lut: string;
  lighting: string;
  weather: string;
  timeOfDay: string;
  effects: string;
  resolution: string;
  fps: string;
  aspect: string;
  environment: string;
  background: string;
  camera: string;
  exportMode: string;
  autoGenerated: string;
}

const UI: Record<SmartMetadataLocale, MetadataUiStrings> = {
  en: {
    panelTitle: 'Video Information',
    platform: 'Platform',
    language: 'Language',
    titles: 'Title suggestions',
    description: 'Description',
    hashtags: 'Hashtags',
    keywords: 'Keywords',
    copyTitle: 'Copy Title',
    copyDescription: 'Copy Description',
    copyHashtags: 'Copy Hashtags',
    copyAll: 'Copy All',
    regenerate: 'Regenerate',
    copied: 'Copied to clipboard',
    copyFailed: 'Copy failed',
    createdWith: 'Created with AnimaStage Lite',
    character: 'Character',
    motion: 'Motion',
    stage: 'Stage',
    visualStyle: 'Visual Style',
    shaderPack: 'Shader Pack',
    lut: 'LUT / Grade',
    lighting: 'Lighting',
    weather: 'Weather',
    timeOfDay: 'Time of Day',
    effects: 'Effects',
    resolution: 'Resolution',
    fps: 'FPS',
    aspect: 'Aspect Ratio',
    environment: 'Environment',
    background: 'Background',
    camera: 'Camera',
    exportMode: 'Export',
    autoGenerated: 'Generated automatically.',
  },
  ja: {
    panelTitle: '動画情報',
    platform: 'プラットフォーム',
    language: '言語',
    titles: 'タイトル候補',
    description: '説明文',
    hashtags: 'ハッシュタグ',
    keywords: 'キーワード',
    copyTitle: 'タイトルをコピー',
    copyDescription: '説明をコピー',
    copyHashtags: 'タグをコピー',
    copyAll: 'すべてコピー',
    regenerate: '再生成',
    copied: 'クリップボードにコピーしました',
    copyFailed: 'コピーに失敗しました',
    createdWith: 'AnimaStage Lite で作成',
    character: 'キャラクター',
    motion: 'モーション',
    stage: 'ステージ',
    visualStyle: 'ビジュアルスタイル',
    shaderPack: 'シェーダーパック',
    lut: 'LUT / グレード',
    lighting: 'ライティング',
    weather: '天候',
    timeOfDay: '時間帯',
    effects: 'エフェクト',
    resolution: '解像度',
    fps: 'FPS',
    aspect: 'アスペクト比',
    environment: '環境',
    background: '背景',
    camera: 'カメラ',
    exportMode: 'エクスポート',
    autoGenerated: '自動生成されました。',
  },
  ru: {
    panelTitle: 'Информация о видео',
    platform: 'Платформа',
    language: 'Язык',
    titles: 'Варианты названия',
    description: 'Описание',
    hashtags: 'Хештеги',
    keywords: 'Ключевые слова',
    copyTitle: 'Копировать название',
    copyDescription: 'Копировать описание',
    copyHashtags: 'Копировать теги',
    copyAll: 'Копировать всё',
    regenerate: 'Перегенерировать',
    copied: 'Скопировано в буфер обмена',
    copyFailed: 'Не удалось скопировать',
    createdWith: 'Создано в AnimaStage Lite',
    character: 'Персонаж',
    motion: 'Моушн',
    stage: 'Сцена',
    visualStyle: 'Визуальный стиль',
    shaderPack: 'Шейдер-пак',
    lut: 'LUT / грейд',
    lighting: 'Освещение',
    weather: 'Погода',
    timeOfDay: 'Время суток',
    effects: 'Эффекты',
    resolution: 'Разрешение',
    fps: 'FPS',
    aspect: 'Соотношение сторон',
    environment: 'Окружение',
    background: 'Фон',
    camera: 'Камера',
    exportMode: 'Экспорт',
    autoGenerated: 'Сгенерировано автоматически.',
  },
  es: {
    panelTitle: 'Información del video',
    platform: 'Plataforma',
    language: 'Idioma',
    titles: 'Sugerencias de título',
    description: 'Descripción',
    hashtags: 'Hashtags',
    keywords: 'Palabras clave',
    copyTitle: 'Copiar título',
    copyDescription: 'Copiar descripción',
    copyHashtags: 'Copiar hashtags',
    copyAll: 'Copiar todo',
    regenerate: 'Regenerar',
    copied: 'Copiado al portapapeles',
    copyFailed: 'Error al copiar',
    createdWith: 'Creado con AnimaStage Lite',
    character: 'Personaje',
    motion: 'Motion',
    stage: 'Escenario',
    visualStyle: 'Estilo visual',
    shaderPack: 'Pack de shaders',
    lut: 'LUT / grado',
    lighting: 'Iluminación',
    weather: 'Clima',
    timeOfDay: 'Hora del día',
    effects: 'Efectos',
    resolution: 'Resolución',
    fps: 'FPS',
    aspect: 'Relación de aspecto',
    environment: 'Entorno',
    background: 'Fondo',
    camera: 'Cámara',
    exportMode: 'Exportación',
    autoGenerated: 'Generado automáticamente.',
  },
  fr: {
    panelTitle: 'Informations vidéo',
    platform: 'Plateforme',
    language: 'Langue',
    titles: 'Suggestions de titre',
    description: 'Description',
    hashtags: 'Hashtags',
    keywords: 'Mots-clés',
    copyTitle: 'Copier le titre',
    copyDescription: 'Copier la description',
    copyHashtags: 'Copier les hashtags',
    copyAll: 'Tout copier',
    regenerate: 'Régénérer',
    copied: 'Copié dans le presse-papiers',
    copyFailed: 'Échec de la copie',
    createdWith: 'Créé avec AnimaStage Lite',
    character: 'Personnage',
    motion: 'Motion',
    stage: 'Scène',
    visualStyle: 'Style visuel',
    shaderPack: 'Pack shader',
    lut: 'LUT / grade',
    lighting: 'Éclairage',
    weather: 'Météo',
    timeOfDay: 'Moment de la journée',
    effects: 'Effets',
    resolution: 'Résolution',
    fps: 'FPS',
    aspect: 'Format',
    environment: 'Environnement',
    background: 'Arrière-plan',
    camera: 'Caméra',
    exportMode: 'Export',
    autoGenerated: 'Généré automatiquement.',
  },
  de: {
    panelTitle: 'Video-Informationen',
    platform: 'Plattform',
    language: 'Sprache',
    titles: 'Titelvorschläge',
    description: 'Beschreibung',
    hashtags: 'Hashtags',
    keywords: 'Schlüsselwörter',
    copyTitle: 'Titel kopieren',
    copyDescription: 'Beschreibung kopieren',
    copyHashtags: 'Hashtags kopieren',
    copyAll: 'Alles kopieren',
    regenerate: 'Neu generieren',
    copied: 'In die Zwischenablage kopiert',
    copyFailed: 'Kopieren fehlgeschlagen',
    createdWith: 'Erstellt mit AnimaStage Lite',
    character: 'Charakter',
    motion: 'Motion',
    stage: 'Bühne',
    visualStyle: 'Visueller Stil',
    shaderPack: 'Shader-Pack',
    lut: 'LUT / Grade',
    lighting: 'Beleuchtung',
    weather: 'Wetter',
    timeOfDay: 'Tageszeit',
    effects: 'Effekte',
    resolution: 'Auflösung',
    fps: 'FPS',
    aspect: 'Seitenverhältnis',
    environment: 'Umgebung',
    background: 'Hintergrund',
    camera: 'Kamera',
    exportMode: 'Export',
    autoGenerated: 'Automatisch generiert.',
  },
  pt: {
    panelTitle: 'Informações do vídeo',
    platform: 'Plataforma',
    language: 'Idioma',
    titles: 'Sugestões de título',
    description: 'Descrição',
    hashtags: 'Hashtags',
    keywords: 'Palavras-chave',
    copyTitle: 'Copiar título',
    copyDescription: 'Copiar descrição',
    copyHashtags: 'Copiar hashtags',
    copyAll: 'Copiar tudo',
    regenerate: 'Regenerar',
    copied: 'Copiado para a área de transferência',
    copyFailed: 'Falha ao copiar',
    createdWith: 'Criado com AnimaStage Lite',
    character: 'Personagem',
    motion: 'Motion',
    stage: 'Palco',
    visualStyle: 'Estilo visual',
    shaderPack: 'Pacote de shader',
    lut: 'LUT / grade',
    lighting: 'Iluminação',
    weather: 'Clima',
    timeOfDay: 'Horário',
    effects: 'Efeitos',
    resolution: 'Resolução',
    fps: 'FPS',
    aspect: 'Proporção',
    environment: 'Ambiente',
    background: 'Fundo',
    camera: 'Câmera',
    exportMode: 'Exportação',
    autoGenerated: 'Gerado automaticamente.',
  },
};

export function getMetadataUi(locale: SmartMetadataLocale): MetadataUiStrings {
  return UI[locale] ?? UI.en;
}

export const PLATFORM_LABELS: Record<
  import('./types').SocialPlatformId,
  string
> = {
  youtube: 'YouTube',
  youtube_shorts: 'YouTube Shorts',
  tiktok: 'TikTok',
  instagram_reels: 'Instagram Reels',
  x: 'X',
};

/** Human-readable preset labels (English keys → localized where useful). */
export function labelPreset(
  locale: SmartMetadataLocale,
  category: string,
  value: string
): string {
  const key = `${category}:${value}`;
  const table: Record<string, Partial<Record<SmartMetadataLocale, string>>> = {
    'scene:studio': { ja: 'スタジオ', ru: 'Студия', es: 'Estudio' },
    'scene:sunset': { ja: '夕焼け', ru: 'Закат', es: 'Atardecer' },
    'scene:nightclub': { ja: 'ナイトクラブ', ru: 'Клуб' },
    'scene:cyber': { ja: 'サイバー', ru: 'Кибер' },
    'light:neon': { ja: 'ネオン', ru: 'Неон' },
    'light:concert': { ja: 'コンサート', ru: 'Концерт' },
    'weather:rain': { ja: '雨', ru: 'Дождь', es: 'Lluvia' },
    'weather:snow': { ja: '雪', ru: 'Снег', es: 'Nieve' },
    'weather:fog': { ja: '霧', ru: 'Туман', es: 'Niebla' },
    'time:night': { ja: '夜', ru: 'Ночь', es: 'Noche' },
    'time:golden_hour': { ja: 'ゴールデンアワー', ru: 'Золотой час' },
    'time:day': { ja: '昼', ru: 'День', es: 'Día' },
  };
  const row = table[key];
  if (row?.[locale]) return row[locale]!;
  return value.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}
