import type { RenderPipeline2State } from './types';

export const DEFAULT_RENDER_PIPELINE_2: RenderPipeline2State = {
  version: 2,
  enabled: true,
  activePreset: 'anime',
  gi: {
    mode: 'ssgi',
    quality: 'medium',
    intensity: 0.55,
    colorBleeding: 0.35,
    indirectBounce: 0.4,
    temporalAccumulation: true,
    halfResolution: true,
    denoiser: true,
    normalAware: true,
    sunBounce: 0.45,
    skyBounce: 0.55,
  },
  ao: {
    mode: 'hybrid',
    intensity: 1.0,
    radius: 0.55,
    power: 1.2,
    samples: 12,
    temporal: true,
    contactAo: true,
    halfRes: true,
  },
  contactShadows: {
    enabled: true,
    opacity: 0.55,
    scale: 12,
    blur: 2.2,
    far: 8,
    characters: true,
    props: true,
    ground: true,
  },
  reflections: {
    mode: 'hybrid',
    intensity: 0.65,
    probeBlending: true,
    parallaxCorrected: true,
    autoProbes: false,
  },
  volumetrics: {
    fogEnabled: false,
    heightFog: 0.15,
    distanceFog: 0.2,
    scattering: 0.25,
    godRays: false,
    godRaysIntensity: 0.35,
    lightShafts: 0.2,
    cloudShadows: 0,
  },
  bloom: {
    style: 'cinematic',
    enabled: true,
    intensity: 0.48,
    threshold: 0.55,
    radius: 0.75,
    lensDirt: 0,
  },
  color: {
    toneMapper: 'aces',
    exposure: 1.05,
    temperature: 0,
    contrast: 0.08,
    gamma: 1,
    whiteBalance: 0,
    lutIntensity: 1,
    gradeAlias: 'cinematic',
  },
  materials: {
    look: 'anime',
    skinEnabled: true,
    skinSoftness: 0.55,
    skinBackLight: 0.35,
    eyeWetness: 0.45,
    hairAnisotropy: 0.6,
    autoConvert: true,
  },
  lights: {
    sunIntensity: 1.15,
    skyIntensity: 0.85,
    ambientIntensity: 0.55,
    temperature: 5600,
    shadowResolution: 'high',
    volumetrics: 0.2,
  },
  camera: {
    dof: false,
    bokehScale: 1.4,
    chromaticAberration: 0.0008,
    lensDistortion: 0,
    filmGrain: 0,
    motionBlur: 0,
    vignette: 0.25,
    sharpen: 0.1,
    autoExposure: false,
    focusTracking: true,
  },
  performance: {
    backend: 'auto',
    dynamicResolution: true,
    temporalUpscale: false,
    adaptiveSampling: true,
    lod: true,
    frustumCulling: true,
    occlusionCulling: false,
    gpuInstancing: true,
    autoQualityScale: true,
  },
};
