import type { StylePackFxConfig } from '../types';

/** Reusable FX patches — inspired by MMD / anime-game looks, mapped to WebGL post-FX. */
export const FX_TEMPLATES: Record<string, StylePackFxConfig> = {
  neutral: {},
  classicMmd: {
    bloomEnabled: true,
    bloomIntensity: 0.32,
    bloomThreshold: 0.52,
    colorGrade: 'neutral',
    lightPreset: 'natural',
    scenePreset: 'studio',
    aoIntensity: 2.8,
    materialDetailing: true,
    materialSmoothing: 0.35,
    toneExposure: 0.95,
  },
  mikuMiku: {
    bloomEnabled: true,
    bloomIntensity: 0.42,
    bloomThreshold: 0.52,
    colorGrade: 'anime',
    lightPreset: 'anime',
    scenePreset: 'studio',
    materialDetailing: true,
    materialSmoothing: 0.42,
    ssaoEnabled: true,
    ssaoIntensity: 0.85,
  },
  adultShader: {
    bloomEnabled: true,
    bloomIntensity: 0.35,
    colorGrade: 'cinematic',
    lightPreset: 'rim',
    dofEnabled: true,
    dofBokehScale: 2.2,
    materialSmoothing: 0.55,
    toneExposure: 0.88,
  },
  nchl: {
    bloomEnabled: true,
    bloomIntensity: 0.32,
    bloomThreshold: 0.55,
    colorGrade: 'neutral',
    lightPreset: 'natural',
    ssaoEnabled: true,
    ssaoIntensity: 1.2,
    aoIntensity: 4.2,
    materialDetailing: true,
  },
  ikPolish: {
    bloomEnabled: true,
    bloomIntensity: 0.28,
    bloomThreshold: 0.55,
    colorGrade: 'warm',
    materialSmoothing: 0.62,
    materialDetailing: true,
    toneExposure: 1.02,
  },
  autoLuminous: {
    bloomEnabled: true,
    bloomIntensity: 0.48,
    bloomThreshold: 0.55,
    colorGrade: 'anime',
    lightPreset: 'anime',
    materialDetailing: true,
    toneExposure: 1.05,
  },
  excellentShadow: {
    ssaoEnabled: true,
    ssaoIntensity: 1.45,
    aoIntensity: 4.8,
    bloomEnabled: true,
    bloomIntensity: 0.22,
    bloomThreshold: 0.58,
    colorGrade: 'neutral',
    lightPreset: 'spotlight',
    floorReflection: 0.55,
  },
  diffusion: {
    bloomEnabled: true,
    bloomIntensity: 0.55,
    bloomThreshold: 0.45,
    bloomRadius: 0.85,
    dofEnabled: true,
    dofBokehScale: 3.5,
    colorGrade: 'anime',
    materialSmoothing: 0.68,
  },
  hgsao: {
    ssaoEnabled: true,
    ssaoIntensity: 1.65,
    aoIntensity: 5.2,
    bloomEnabled: false,
    colorGrade: 'neutral',
    environmentIntensity: 0.72,
  },
  powerDof: {
    dofEnabled: true,
    dofBokehScale: 4.2,
    dofFocusDistance: 12,
    bloomEnabled: true,
    bloomIntensity: 0.15,
    colorGrade: 'cinematic',
    vignetteEnabled: true,
    vignetteIntensity: 0.35,
  },
  workingFloor: {
    floorReflection: 0.88,
    environmentIntensity: 0.82,
    bloomEnabled: true,
    bloomIntensity: 0.2,
    colorGrade: 'neutral',
    scenePreset: 'studio',
    lightPreset: 'natural',
  },
  objectLuminous: {
    bloomEnabled: true,
    bloomIntensity: 0.62,
    bloomThreshold: 0.42,
    colorGrade: 'anime',
    materialDetailing: true,
    toneExposure: 1.08,
  },
  animeToon: {
    bloomEnabled: false,
    colorGrade: 'anime',
    lightPreset: 'anime',
    materialSmoothing: 0.25,
    materialDetailing: false,
    toneExposure: 1.05,
  },
  softToon: {
    bloomEnabled: true,
    bloomIntensity: 0.28,
    colorGrade: 'anime',
    lightPreset: 'rim',
    materialSmoothing: 0.72,
    toneExposure: 0.94,
  },
  animeSoft: {
    bloomEnabled: true,
    bloomIntensity: 0.32,
    colorGrade: 'anime',
    lightPreset: 'rim',
    materialSmoothing: 0.68,
    toneExposure: 0.92,
  },
  animeBright: {
    bloomEnabled: true,
    bloomIntensity: 0.52,
    colorGrade: 'anime',
    lightPreset: 'anime',
    toneExposure: 1.12,
    environmentIntensity: 0.95,
  },
  animeFlat: {
    bloomEnabled: false,
    colorGrade: 'anime',
    materialSmoothing: 0.18,
    materialDetailing: false,
    toneExposure: 1.08,
  },
  animeCel: {
    bloomEnabled: false,
    colorGrade: 'anime',
    lightPreset: 'spotlight',
    materialSmoothing: 0.22,
    chromaticAberration: 0.002,
  },
  animeStudio: {
    bloomEnabled: true,
    bloomIntensity: 0.28,
    colorGrade: 'neutral',
    scenePreset: 'studio',
    lightPreset: 'natural',
    materialDetailing: true,
    ssaoEnabled: true,
  },
  animeIdol: {
    bloomEnabled: true,
    bloomIntensity: 0.45,
    colorGrade: 'anime',
    lightPreset: 'concert',
    particlesEnabled: true,
    particlePreset: 'sparkles',
    particleIntensity: 0.35,
  },
  animeStage: {
    bloomEnabled: true,
    bloomIntensity: 0.38,
    scenePreset: 'stage',
    lightPreset: 'concert',
    colorGrade: 'anime',
    floorReflection: 0.72,
  },
  animeNight: {
    bloomEnabled: true,
    bloomIntensity: 0.42,
    colorGrade: 'cold',
    lightPreset: 'neon',
    scenePreset: 'nightclub',
    toneExposure: 0.82,
  },
  animeBloom: {
    bloomEnabled: true,
    bloomIntensity: 0.65,
    bloomThreshold: 0.38,
    colorGrade: 'anime',
    lightPreset: 'anime',
  },
  animePastel: {
    bloomEnabled: true,
    bloomIntensity: 0.25,
    colorGrade: 'warm',
    lightPreset: 'rim',
    materialSmoothing: 0.75,
    toneExposure: 1.05,
  },
  genshin: {
    bloomEnabled: true,
    bloomIntensity: 0.38,
    colorGrade: 'anime',
    lightPreset: 'natural',
    scenePreset: 'outdoor',
    environmentIntensity: 0.88,
    materialDetailing: true,
    toneExposure: 1.0,
  },
  honkai: {
    bloomEnabled: true,
    bloomIntensity: 0.48,
    colorGrade: 'cinematic',
    lightPreset: 'rim',
    chromaticAberration: 0.004,
    ssaoEnabled: true,
    toneExposure: 0.92,
  },
  zenless: {
    bloomEnabled: true,
    bloomIntensity: 0.55,
    colorGrade: 'vaporwave',
    lightPreset: 'neon',
    scenePreset: 'cyber',
    chromaticAberration: 0.006,
  },
  blueArchive: {
    bloomEnabled: true,
    bloomIntensity: 0.35,
    colorGrade: 'anime',
    lightPreset: 'anime',
    toneExposure: 1.08,
    materialSmoothing: 0.58,
  },
  wuthering: {
    bloomEnabled: true,
    bloomIntensity: 0.42,
    colorGrade: 'cinematic',
    lightPreset: 'natural',
    scenePreset: 'outdoor',
    godRaysEnabled: true,
    toneExposure: 0.9,
  },
  arknights: {
    bloomEnabled: false,
    colorGrade: 'noir',
    lightPreset: 'spotlight',
    scenePreset: 'warehouse',
    ssaoEnabled: true,
    toneExposure: 0.85,
  },
  azurLane: {
    bloomEnabled: true,
    bloomIntensity: 0.4,
    colorGrade: 'anime',
    lightPreset: 'concert',
    scenePreset: 'stage',
    floorReflection: 0.65,
  },
  nikke: {
    bloomEnabled: true,
    bloomIntensity: 0.52,
    colorGrade: 'cold',
    lightPreset: 'neon',
    scenePreset: 'cyber',
    chromaticAberration: 0.005,
  },
  pgr: {
    bloomEnabled: true,
    bloomIntensity: 0.45,
    colorGrade: 'noir',
    lightPreset: 'neon',
    scenePreset: 'cyber',
    vignetteEnabled: true,
    vignetteIntensity: 0.42,
  },
  hollywood: {
    bloomEnabled: true,
    bloomIntensity: 0.22,
    colorGrade: 'cinematic',
    lightPreset: 'rim',
    dofEnabled: true,
    vignetteEnabled: true,
    toneExposure: 0.88,
  },
  blockbuster: {
    bloomEnabled: true,
    bloomIntensity: 0.35,
    colorGrade: 'cinematic',
    lightPreset: 'concert',
    chromaticAberration: 0.008,
    toneExposure: 0.95,
  },
  movie: {
    dofEnabled: true,
    dofBokehScale: 3.8,
    bloomEnabled: true,
    bloomIntensity: 0.18,
    colorGrade: 'cinematic',
    vignetteEnabled: true,
  },
  netflix: {
    colorGrade: 'cinematic',
    lightPreset: 'natural',
    bloomEnabled: true,
    bloomIntensity: 0.15,
    toneExposure: 0.86,
    vignetteEnabled: true,
    vignetteIntensity: 0.28,
  },
  drama: {
    colorGrade: 'warm',
    lightPreset: 'natural',
    dofEnabled: true,
    bloomEnabled: false,
    toneExposure: 0.84,
  },
  warmFilm: {
    colorGrade: 'warm',
    bloomEnabled: true,
    bloomIntensity: 0.2,
    vignetteEnabled: true,
    vignetteIntensity: 0.32,
    toneExposure: 0.9,
  },
  coldFilm: {
    colorGrade: 'cold',
    bloomEnabled: true,
    bloomIntensity: 0.15,
    toneExposure: 0.82,
    vignetteEnabled: true,
  },
  vintage: {
    colorGrade: 'warm',
    vignetteEnabled: true,
    vignetteIntensity: 0.48,
    chromaticAberration: 0.012,
    bloomEnabled: true,
    bloomIntensity: 0.12,
    toneExposure: 0.78,
  },
  dream: {
    bloomEnabled: true,
    bloomIntensity: 0.55,
    bloomThreshold: 0.35,
    colorGrade: 'anime',
    dofEnabled: true,
    dofBokehScale: 2.8,
    materialSmoothing: 0.72,
  },
  documentary: {
    colorGrade: 'neutral',
    bloomEnabled: false,
    lightPreset: 'natural',
    toneExposure: 0.92,
    materialDetailing: true,
  },
  cyberpunk: {
    bloomEnabled: true,
    bloomIntensity: 0.58,
    colorGrade: 'vaporwave',
    lightPreset: 'neon',
    scenePreset: 'cyber',
    chromaticAberration: 0.01,
  },
  tokyoNight: {
    bloomEnabled: true,
    bloomIntensity: 0.48,
    colorGrade: 'cold',
    lightPreset: 'neon',
    scenePreset: 'nightclub',
    weatherPreset: 'rain',
    toneExposure: 0.78,
  },
  rgb: {
    bloomEnabled: true,
    bloomIntensity: 0.62,
    chromaticAberration: 0.018,
    colorGrade: 'vaporwave',
    lightPreset: 'neon',
  },
  purpleNeon: {
    bloomEnabled: true,
    bloomIntensity: 0.55,
    colorGrade: 'vaporwave',
    lightPreset: 'neon',
    scenePreset: 'cyber',
  },
  blueNeon: {
    bloomEnabled: true,
    bloomIntensity: 0.5,
    colorGrade: 'cold',
    lightPreset: 'neon',
    scenePreset: 'cyber',
  },
  synthwave: {
    bloomEnabled: true,
    bloomIntensity: 0.58,
    colorGrade: 'vaporwave',
    lightPreset: 'neon',
    scenePreset: 'cyber',
    floorReflection: 0.82,
  },
  vaporwave: {
    bloomEnabled: true,
    bloomIntensity: 0.52,
    colorGrade: 'vaporwave',
    lightPreset: 'neon',
    chromaticAberration: 0.008,
  },
  tron: {
    bloomEnabled: true,
    bloomIntensity: 0.65,
    bloomThreshold: 0.35,
    colorGrade: 'cold',
    lightPreset: 'neon',
    scenePreset: 'cyber',
    floorReflection: 0.95,
  },
  bladeRunner: {
    bloomEnabled: true,
    bloomIntensity: 0.42,
    colorGrade: 'noir',
    lightPreset: 'neon',
    weatherPreset: 'rain',
    vignetteEnabled: true,
    toneExposure: 0.72,
  },
  magic: {
    bloomEnabled: true,
    bloomIntensity: 0.48,
    colorGrade: 'anime',
    particlesEnabled: true,
    particlePreset: 'sparkles',
    particleIntensity: 0.55,
  },
  crystal: {
    bloomEnabled: true,
    bloomIntensity: 0.38,
    colorGrade: 'cold',
    environmentIntensity: 0.92,
    floorReflection: 0.88,
    materialSmoothing: 0.58,
  },
  moon: {
    bloomEnabled: true,
    bloomIntensity: 0.32,
    colorGrade: 'cold',
    lightPreset: 'rim',
    scenePreset: 'outdoor',
    toneExposure: 0.75,
  },
  aurora: {
    bloomEnabled: true,
    bloomIntensity: 0.45,
    colorGrade: 'cold',
    godRaysEnabled: true,
    particlesEnabled: true,
    particlePreset: 'fireflies',
  },
  fairy: {
    bloomEnabled: true,
    bloomIntensity: 0.42,
    colorGrade: 'anime',
    particlesEnabled: true,
    particlePreset: 'petals',
    materialSmoothing: 0.7,
  },
  divine: {
    bloomEnabled: true,
    bloomIntensity: 0.55,
    godRaysEnabled: true,
    colorGrade: 'warm',
    lightPreset: 'natural',
    toneExposure: 1.05,
  },
  mystic: {
    bloomEnabled: true,
    bloomIntensity: 0.38,
    colorGrade: 'vaporwave',
    ssaoEnabled: true,
  },
  spirit: {
    bloomEnabled: true,
    bloomIntensity: 0.48,
    bloomThreshold: 0.4,
    colorGrade: 'anime',
    particlesEnabled: true,
    particlePreset: 'dust',
  },
  fantasyWorld: {
    bloomEnabled: true,
    bloomIntensity: 0.4,
    colorGrade: 'anime',
    scenePreset: 'outdoor',
    godRaysEnabled: true,
    environmentIntensity: 0.9,
  },
  morning: {
    colorGrade: 'warm',
    lightPreset: 'natural',
    toneExposure: 1.05,
    bloomEnabled: true,
    bloomIntensity: 0.18,
    weatherPreset: 'clear',
  },
  goldenHour: {
    colorGrade: 'warm',
    lightPreset: 'natural',
    bloomEnabled: true,
    bloomIntensity: 0.32,
    toneExposure: 0.92,
    scenePreset: 'sunset',
  },
  noon: {
    colorGrade: 'neutral',
    lightPreset: 'natural',
    toneExposure: 1.08,
    bloomEnabled: false,
    scenePreset: 'outdoor',
  },
  sunset: {
    colorGrade: 'warm',
    scenePreset: 'sunset',
    bloomEnabled: true,
    bloomIntensity: 0.38,
    toneExposure: 0.88,
  },
  blueHour: {
    colorGrade: 'cold',
    lightPreset: 'rim',
    toneExposure: 0.78,
    bloomEnabled: true,
    bloomIntensity: 0.22,
  },
  night: {
    colorGrade: 'cold',
    lightPreset: 'neon',
    scenePreset: 'nightclub',
    toneExposure: 0.72,
    bloomEnabled: true,
    bloomIntensity: 0.35,
  },
  rain: {
    weatherPreset: 'rain',
    colorGrade: 'cold',
    toneExposure: 0.82,
    bloomEnabled: true,
    bloomIntensity: 0.25,
  },
  fog: {
    weatherPreset: 'fog',
    colorGrade: 'neutral',
    toneExposure: 0.78,
    bloomEnabled: false,
  },
  snow: {
    weatherPreset: 'snow',
    colorGrade: 'cold',
    particlesEnabled: true,
    particlePreset: 'snow',
    toneExposure: 0.95,
  },
  cloudy: {
    colorGrade: 'neutral',
    lightPreset: 'natural',
    toneExposure: 0.88,
    environmentIntensity: 0.62,
    bloomEnabled: false,
  },
  studioPortrait: {
    scenePreset: 'studio',
    lightPreset: 'natural',
    dofEnabled: true,
    bloomEnabled: true,
    bloomIntensity: 0.15,
    colorGrade: 'neutral',
    materialDetailing: true,
  },
  beauty: {
    bloomEnabled: true,
    bloomIntensity: 0.22,
    materialSmoothing: 0.72,
    colorGrade: 'warm',
    lightPreset: 'rim',
    dofEnabled: true,
  },
  fashion: {
    bloomEnabled: true,
    bloomIntensity: 0.18,
    colorGrade: 'neutral',
    lightPreset: 'spotlight',
    scenePreset: 'studio',
    materialDetailing: true,
  },
  softbox: {
    bloomEnabled: true,
    bloomIntensity: 0.12,
    colorGrade: 'neutral',
    lightPreset: 'natural',
    materialSmoothing: 0.55,
    toneExposure: 1.0,
  },
  hdr: {
    bloomEnabled: true,
    bloomIntensity: 0.28,
    toneExposure: 1.15,
    colorGrade: 'cinematic',
    environmentIntensity: 1.0,
    ssaoEnabled: true,
  },
  product: {
    bloomEnabled: false,
    colorGrade: 'neutral',
    scenePreset: 'studio',
    lightPreset: 'spotlight',
    materialDetailing: true,
    floorReflection: 0.55,
  },
  whiteStudio: {
    scenePreset: 'studio',
    colorGrade: 'neutral',
    toneExposure: 1.12,
    bloomEnabled: false,
    environmentIntensity: 0.95,
  },
  blackStudio: {
    scenePreset: 'studio',
    colorGrade: 'noir',
    toneExposure: 0.72,
    vignetteEnabled: true,
    bloomEnabled: true,
    bloomIntensity: 0.15,
  },
  sketch: {
    bloomEnabled: false,
    colorGrade: 'neutral',
    materialSmoothing: 0.12,
    materialDetailing: false,
    toneExposure: 1.05,
  },
  comic: {
    bloomEnabled: false,
    colorGrade: 'anime',
    chromaticAberration: 0.004,
    materialSmoothing: 0.2,
    toneExposure: 1.1,
  },
  manga: {
    bloomEnabled: false,
    colorGrade: 'noir',
    materialSmoothing: 0.15,
    vignetteEnabled: true,
    toneExposure: 1.08,
  },
  watercolor: {
    bloomEnabled: true,
    bloomIntensity: 0.22,
    colorGrade: 'warm',
    materialSmoothing: 0.78,
    toneExposure: 0.95,
  },
  oilPainting: {
    bloomEnabled: true,
    bloomIntensity: 0.18,
    colorGrade: 'warm',
    materialSmoothing: 0.65,
    vignetteEnabled: true,
    toneExposure: 0.88,
  },
  pixelArt: {
    bloomEnabled: false,
    smaaEnabled: false,
    materialSmoothing: 0.08,
    colorGrade: 'anime',
    toneExposure: 1.05,
  },
  ink: {
    bloomEnabled: false,
    colorGrade: 'noir',
    materialSmoothing: 0.1,
    vignetteEnabled: true,
    toneExposure: 1.02,
  },
  pastelStylized: {
    bloomEnabled: true,
    bloomIntensity: 0.2,
    colorGrade: 'warm',
    materialSmoothing: 0.8,
    toneExposure: 1.05,
  },
  chalk: {
    bloomEnabled: false,
    colorGrade: 'neutral',
    materialSmoothing: 0.85,
    toneExposure: 1.08,
    environmentIntensity: 0.55,
  },
};
