import type { CinematicLightingPresetId, CinematicLookPatch } from '../types';

export const CINEMATIC_LIGHTING_LABELS: Record<CinematicLightingPresetId, string> = {
  anime_soft: 'Anime Soft',
  studio: 'Studio',
  golden_hour: 'Golden Hour',
  sunset: 'Sunset',
  night: 'Night',
  cyberpunk: 'Cyberpunk',
  fantasy: 'Fantasy',
  concert: 'Concert',
  moonlight: 'Moonlight',
  indoor: 'Indoor',
  outdoor: 'Outdoor',
};

const PRESETS: Record<CinematicLightingPresetId, CinematicLookPatch> = {
  anime_soft: {
    visualFx: {
      scenePreset: 'stage',
      lightPreset: 'natural',
      colorGrade: 'anime',
      bloomEnabled: true,
      bloomIntensity: 0.28,
      bloomThreshold: 0.78,
      vignetteEnabled: true,
      vignetteIntensity: 0.18,
      toneExposure: 0.92,
      environmentIntensity: 0.72,
      ssaoEnabled: true,
      ssaoIntensity: 0.65,
      postFxStackEnabled: true,
      smaaEnabled: true,
    },
    sceneComposer: {
      skyPreset: 'blue',
      visualStyle: 'anime',
      exposure: 0.92,
      saturation: 1.08,
      effectLevels: { bloom: 'low', ao: 'low', reflection: 'medium', dof: 'off' },
    },
    characterQuality: 'hd',
  },
  studio: {
    visualFx: {
      scenePreset: 'studio',
      lightPreset: 'natural',
      colorGrade: 'neutral',
      bloomEnabled: false,
      ssaoEnabled: true,
      ssaoIntensity: 0.9,
      toneExposure: 0.9,
      environmentIntensity: 0.68,
      postFxStackEnabled: true,
    },
    sceneComposer: {
      skyPreset: 'blue',
      visualStyle: 'realistic',
      materialOverride: 'studio',
      effectLevels: { bloom: 'off', ao: 'medium', reflection: 'high', dof: 'off' },
    },
  },
  golden_hour: {
    visualFx: {
      scenePreset: 'sunset',
      lightPreset: 'natural',
      colorGrade: 'warm',
      bloomEnabled: true,
      bloomIntensity: 0.24,
      toneExposure: 0.88,
      environmentIntensity: 0.8,
      ssaoEnabled: true,
    },
    sceneComposer: {
      skyPreset: 'sunset',
      sunElevation: 18,
      sunAzimuth: 250,
      sunColor: '#ffd4a8',
      exposure: 0.88,
      temperature: 0.25,
      effectLevels: { bloom: 'low', ao: 'medium', reflection: 'medium', dof: 'off' },
    },
  },
  sunset: {
    visualFx: {
      scenePreset: 'sunset',
      colorGrade: 'warm',
      bloomEnabled: true,
      bloomIntensity: 0.32,
      bloomThreshold: 0.7,
      toneExposure: 0.85,
      vignetteEnabled: true,
      vignetteIntensity: 0.28,
    },
    sceneComposer: {
      skyPreset: 'sunset',
      sunElevation: 8,
      exposure: 0.85,
      saturation: 1.12,
      effectLevels: { bloom: 'medium', ao: 'low', reflection: 'low', dof: 'off' },
    },
  },
  night: {
    visualFx: {
      scenePreset: 'nightclub',
      lightPreset: 'neon',
      colorGrade: 'cold',
      bloomEnabled: true,
      bloomIntensity: 0.38,
      toneExposure: 0.72,
      environmentIntensity: 0.45,
      vignetteEnabled: true,
      vignetteIntensity: 0.35,
    },
    sceneComposer: {
      skyPreset: 'night',
      sunElevation: -10,
      exposure: 0.72,
      effectLevels: { bloom: 'medium', ao: 'medium', reflection: 'low', dof: 'off' },
    },
  },
  cyberpunk: {
    visualFx: {
      scenePreset: 'cyber',
      lightPreset: 'neon',
      colorGrade: 'vaporwave',
      bloomEnabled: true,
      bloomIntensity: 0.45,
      bloomThreshold: 0.62,
      chromaticAberration: 0.12,
      toneExposure: 0.78,
      environmentIntensity: 0.55,
    },
    sceneComposer: {
      skyPreset: 'night',
      visualStyle: 'anime',
      sunColor: '#ff00aa',
      exposure: 0.78,
      saturation: 1.2,
      effectLevels: { bloom: 'high', ao: 'medium', reflection: 'medium', dof: 'off' },
    },
    rtxModeEnabled: true,
  },
  fantasy: {
    visualFx: {
      scenePreset: 'stage',
      colorGrade: 'cinematic',
      bloomEnabled: true,
      bloomIntensity: 0.35,
      godRaysEnabled: false,
      toneExposure: 0.9,
      environmentIntensity: 0.85,
      particlesEnabled: true,
      particlePreset: 'sparkles',
      particleIntensity: 0.35,
    },
    sceneComposer: {
      skyPreset: 'fantasy',
      visualStyle: 'anime',
      fogEnabled: true,
      fogDensity: 0.08,
      effectLevels: { bloom: 'medium', ao: 'low', reflection: 'medium', dof: 'low' },
    },
  },
  concert: {
    visualFx: {
      scenePreset: 'nightclub',
      lightPreset: 'concert',
      colorGrade: 'cinematic',
      bloomEnabled: true,
      bloomIntensity: 0.52,
      bloomThreshold: 0.58,
      toneExposure: 0.82,
      vignetteEnabled: true,
      vignetteIntensity: 0.22,
    },
    sceneComposer: {
      skyPreset: 'night',
      visualStyle: 'anime',
      effectLevels: { bloom: 'high', ao: 'low', reflection: 'high', dof: 'off' },
    },
  },
  moonlight: {
    visualFx: {
      scenePreset: 'nightclub',
      colorGrade: 'cold',
      bloomEnabled: true,
      bloomIntensity: 0.18,
      toneExposure: 0.68,
      environmentIntensity: 0.4,
      ssaoEnabled: true,
      ssaoIntensity: 0.75,
    },
    sceneComposer: {
      skyPreset: 'night',
      sunColor: '#a8c8ff',
      sunElevation: 35,
      exposure: 0.68,
      temperature: -0.2,
      effectLevels: { bloom: 'low', ao: 'medium', reflection: 'low', dof: 'off' },
    },
  },
  indoor: {
    visualFx: {
      scenePreset: 'studio',
      lightPreset: 'natural',
      colorGrade: 'neutral',
      bloomEnabled: false,
      toneExposure: 0.94,
      environmentIntensity: 0.6,
      ssaoEnabled: true,
      ssaoIntensity: 0.55,
    },
    sceneComposer: {
      skyPreset: 'cloudy',
      visualStyle: 'realistic',
      exposure: 0.94,
      effectLevels: { bloom: 'off', ao: 'low', reflection: 'medium', dof: 'low' },
    },
  },
  outdoor: {
    visualFx: {
      scenePreset: 'outdoor',
      lightPreset: 'natural',
      colorGrade: 'neutral',
      bloomEnabled: true,
      bloomIntensity: 0.15,
      toneExposure: 0.95,
      environmentIntensity: 0.88,
      ssaoEnabled: true,
      ssaoIntensity: 0.5,
    },
    sceneComposer: {
      skyPreset: 'blue',
      sunElevation: 42,
      exposure: 0.95,
      effectLevels: { bloom: 'low', ao: 'low', reflection: 'medium', dof: 'off' },
    },
  },
};

export function getCinematicLightingPatch(id: CinematicLightingPresetId): CinematicLookPatch {
  return PRESETS[id] ?? PRESETS.anime_soft;
}
