import type { SceneFxDefinition, SceneFxInstance, SceneFxParameterValue } from './types';

export const BUILTIN_SCENE_FX: SceneFxDefinition[] = [
  {
    id: 'weather.rain',
    version: 1,
    name: 'Cinematic Rain',
    description: 'World-space rain with depth-aware foreground coverage.',
    category: 'weather',
    mount: 'world',
    tags: ['rain', 'weather', 'cinematic'],
    requires: { depth: true, compute: true },
    fallbackEffectId: 'legacy.weather.rain',
  },
  {
    id: 'weather.snow',
    version: 1,
    name: 'Soft Snow',
    description: 'Wind-driven snow particles with adaptive density.',
    category: 'weather',
    mount: 'world',
    tags: ['snow', 'weather', 'winter'],
    requires: { depth: true, compute: true },
    fallbackEffectId: 'legacy.weather.snow',
  },
  {
    id: 'weather.ash',
    version: 1,
    name: 'Falling Ash',
    description: 'Slow turbulent ash for dramatic environments.',
    category: 'weather',
    mount: 'world',
    tags: ['ash', 'apocalypse', 'atmosphere'],
    requires: { depth: true, compute: true },
    fallbackEffectId: 'legacy.particles.dust',
  },
  {
    id: 'weather.mist',
    version: 1,
    name: 'Ground Mist',
    description: 'Low-level depth-aware mist for fog moods (VQ Fog 2.0).',
    category: 'weather',
    mount: 'world',
    tags: ['mist', 'fog', 'atmosphere'],
    requires: { depth: true },
  },
  {
    id: 'environment.stars',
    version: 1,
    name: 'Shining Stars',
    description: 'Procedural night-sky stars.',
    category: 'environment',
    mount: 'background',
    tags: ['stars', 'night', 'sky'],
    requires: {},
  },
  {
    id: 'environment.fireworks',
    version: 1,
    name: 'Fireworks',
    description: 'Timed GPU particle bursts behind and around the cast.',
    category: 'particles',
    mount: 'world',
    tags: ['fireworks', 'festival', 'night'],
    requires: { depth: true, compute: true },
    fallbackEffectId: 'legacy.particles.sparkles',
  },
  {
    id: 'character.aura',
    version: 1,
    name: 'Character Aura',
    description: 'Energy shell driven by the character bounding sphere.',
    category: 'character',
    mount: 'character',
    tags: ['aura', 'energy', 'anime'],
    requires: { character: true, depth: true },
  },
  {
    id: 'character.magic_circle',
    version: 1,
    name: 'Magic Circle',
    description: 'Animated floor effect anchored below the character.',
    category: 'magic',
    mount: 'surface',
    tags: ['magic', 'floor', 'character'],
    requires: { character: true, depth: true },
  },
  {
    id: 'character.hand_trail',
    version: 1,
    name: 'Hand Ribbon',
    description: 'Ribbon trail following a named hand or weapon bone.',
    category: 'character',
    mount: 'character',
    tags: ['trail', 'hand', 'weapon', 'ribbon'],
    requires: { character: true, bones: true, compute: true },
  },
  {
    id: 'audio.pulse',
    version: 1,
    name: 'Music Pulse',
    description: 'Audio-driven bloom, light and particle modulation.',
    category: 'audio',
    mount: 'post',
    tags: ['audio', 'music', 'kick', 'spectrum'],
    requires: { audio: true },
  },
  {
    id: 'character.divine_light',
    version: 1,
    name: 'Divine Light',
    description: 'Golden aura shell for heroic / fantasy shots.',
    category: 'energy',
    mount: 'character',
    tags: ['aura', 'divine', 'gold', 'fantasy'],
    requires: { character: true, depth: true },
    runtimeEffectId: 'character.aura',
  },
  {
    id: 'character.spectral_trail',
    version: 1,
    name: 'Spectral Trail',
    description: 'Ghostly ribbon following the lead hand bone.',
    category: 'anime',
    mount: 'character',
    tags: ['trail', 'ghost', 'spectral'],
    requires: { character: true, bones: true, compute: true },
    runtimeEffectId: 'character.hand_trail',
  },
  {
    id: 'magic.hex_field',
    version: 1,
    name: 'Hex Field',
    description: 'Rotating hex floor sigil under the cast.',
    category: 'magic',
    mount: 'surface',
    tags: ['magic', 'hex', 'floor'],
    requires: { character: true, depth: true },
    runtimeEffectId: 'character.magic_circle',
  },
  {
    id: 'anime.speed_lines',
    version: 1,
    name: 'Speed Lines',
    description: 'Radial motion streaks for action beats.',
    category: 'anime',
    mount: 'foreground',
    tags: ['speed', 'action', 'anime'],
    requires: { depth: true },
    fallbackEffectId: 'legacy.particles.dust',
  },
  {
    id: 'cinematic.lens_flare',
    version: 1,
    name: 'Lens Flare',
    description: 'Camera-facing flare streaks (post stack hint).',
    category: 'cinematic',
    mount: 'post',
    tags: ['flare', 'sun', 'cinematic'],
    requires: {},
  },
  {
    id: 'particles.spark_burst',
    version: 1,
    name: 'Spark Burst',
    description: 'Short celebratory particle pops.',
    category: 'particles',
    mount: 'world',
    tags: ['spark', 'burst', 'celebration'],
    requires: { depth: true, compute: true },
    runtimeEffectId: 'environment.fireworks',
  },
  {
    id: 'energy.charge',
    version: 1,
    name: 'Energy Charge',
    description: 'Pulsing charge aura before a strike.',
    category: 'energy',
    mount: 'character',
    tags: ['charge', 'energy', 'power'],
    requires: { character: true, depth: true },
    runtimeEffectId: 'character.aura',
  },
  {
    id: 'particles.confetti',
    version: 1,
    name: 'Confetti',
    description: 'Celebratory confetti shower for finales.',
    category: 'particles',
    mount: 'world',
    tags: ['confetti', 'party', 'celebration'],
    requires: { depth: true, compute: true },
    runtimeEffectId: 'environment.fireworks',
  },
  {
    id: 'magic.rune_ring',
    version: 1,
    name: 'Rune Ring',
    description: 'Arcane rune circle with slow rotation.',
    category: 'magic',
    mount: 'surface',
    tags: ['rune', 'magic', 'circle'],
    requires: { character: true, depth: true },
    runtimeEffectId: 'character.magic_circle',
  },
  {
    id: 'character.eye_glow',
    version: 1,
    name: 'Eye Glow',
    description: 'Emissive eye highlight for dramatic close-ups.',
    category: 'character',
    tags: ['eyes', 'glow', 'anime'],
    requires: { character: true },
    runtimeEffectId: 'character.aura',
  },
  {
    id: 'cinematic.vignette_pulse',
    version: 1,
    name: 'Vignette Pulse',
    description: 'Breathing vignette for tension beats (post hint).',
    category: 'cinematic',
    mount: 'post',
    tags: ['vignette', 'pulse', 'drama'],
    requires: {},
  },
  {
    id: 'environment.god_rays',
    version: 1,
    name: 'God Rays',
    description: 'Volumetric light shafts when VQ god rays are enabled.',
    category: 'environment',
    mount: 'world',
    tags: ['god rays', 'sun', 'volumetric'],
    requires: { depth: true },
  },
  {
    id: 'anime.impact_flash',
    version: 1,
    name: 'Impact Flash',
    description: 'Short white flash on action hits.',
    category: 'anime',
    mount: 'foreground',
    tags: ['impact', 'flash', 'action'],
    requires: {},
    fallbackEffectId: 'legacy.particles.sparkles',
  },
];

export function getSceneFxDefinition(id: string): SceneFxDefinition | undefined {
  return BUILTIN_SCENE_FX.find((effect) => effect.id === id);
}

export function resolveRuntimeEffectId(effectId: string): string {
  const definition = getSceneFxDefinition(effectId);
  return definition?.runtimeEffectId ?? effectId;
}

export function createSceneFxInstance(
  effectId: string,
  overrides: Partial<SceneFxInstance> = {},
  maxFrames = 120
): SceneFxInstance {
  const definition = getSceneFxDefinition(effectId);
  const now =
    typeof crypto !== 'undefined' && 'randomUUID' in crypto
      ? crypto.randomUUID()
      : `${Date.now()}_${Math.random().toString(36).slice(2)}`;

  const defaultParams: Record<string, SceneFxParameterValue> = { ...overrides.parameters };
  if (effectId === 'character.divine_light' && !defaultParams.color) {
    defaultParams.color = { value: '#ffd966' };
  }
  if (effectId === 'energy.charge' && !defaultParams.color) {
    defaultParams.color = { value: '#66ccff' };
  }

  return {
    id: overrides.id ?? `scene_fx_${now}`,
    effectId,
    effectVersion: definition?.version ?? 1,
    name: overrides.name ?? definition?.name ?? effectId,
    enabled: overrides.enabled ?? true,
    mount: overrides.mount ?? definition?.mount ?? 'world',
    category: overrides.category ?? definition?.category ?? 'environment',
    intensity: overrides.intensity ?? 1,
    quality: overrides.quality ?? 'auto',
    order: overrides.order ?? 0,
    targetModelId: overrides.targetModelId ?? null,
    targetBone: overrides.targetBone ?? null,
    parameters: defaultParams,
    window: overrides.window ?? null,
    keyframes: overrides.keyframes ?? [],
    runtimeError: overrides.runtimeError ?? null,
    favorite: overrides.favorite ?? false,
  };
}
