import type { CameraTemplateDef } from './types';

function t(
  partial: Omit<CameraTemplateDef, 'builtin'> & { builtin?: true }
): CameraTemplateDef {
  return { builtin: true, ...partial };
}

/** Full built-in cinematic camera template catalog. */
export const BUILTIN_CAMERA_TEMPLATES: CameraTemplateDef[] = [
  t({
    id: 'character_showcase',
    label: 'Character Showcase',
    description: 'Reveal full figure with gentle orbit',
    category: 'showcase',
    motion: 'orbit',
    durationScale: 1,
    baseFov: 42,
    radiusMul: 1.15,
    heightFrac: 0.55,
    lookFrac: 0.45,
    easing: 'cinematic',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.12,
    speed: 0.95,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 8, max: 40, preferred: 16 },
    styleTags: ['showcase', 'orbit', 'slow', 'full'],
  }),
  t({
    id: 'idle_presentation',
    label: 'Idle Presentation',
    description: 'Calm hold with micro drift',
    category: 'showcase',
    motion: 'static_hold',
    durationScale: 0.85,
    baseFov: 40,
    radiusMul: 1.05,
    heightFrac: 0.5,
    lookFrac: 0.48,
    easing: 'easeInOut',
    framing: 'auto_reframe',
    followTarget: 'chest',
    dofStrength: 0.18,
    speed: 0.7,
    preferredAspects: ['16:9', '1:1'],
    safe: { min: 7, max: 28, preferred: 14 },
    styleTags: ['idle', 'hold', 'soft'],
  }),
  t({
    id: 'slow_orbit',
    label: 'Slow Orbit',
    description: 'Leisurely cinematic circle',
    category: 'orbit',
    motion: 'orbit',
    durationScale: 1.15,
    baseFov: 40,
    radiusMul: 1.2,
    heightFrac: 0.52,
    lookFrac: 0.42,
    easing: 'catmull',
    framing: 'keep_character',
    followTarget: 'chest',
    dofStrength: 0.15,
    speed: 0.75,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 9, max: 36, preferred: 17 },
    styleTags: ['orbit', 'slow', 'cinematic'],
  }),
  t({
    id: 'fast_orbit',
    label: 'Fast Orbit',
    description: 'Energetic orbit with snap energy',
    category: 'orbit',
    motion: 'orbit_fast',
    durationScale: 0.85,
    baseFov: 38,
    radiusMul: 1.05,
    heightFrac: 0.55,
    lookFrac: 0.5,
    easing: 'catmull',
    framing: 'dynamic',
    followTarget: 'chest',
    dofStrength: 0.1,
    speed: 1.35,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 7, max: 30, preferred: 13 },
    styleTags: ['orbit', 'fast', 'energy'],
  }),
  t({
    id: 'orbit_360',
    label: '360 Orbit',
    description: 'Full revolution around the character',
    category: 'orbit',
    motion: 'orbit_360',
    durationScale: 1.2,
    baseFov: 42,
    radiusMul: 1.25,
    heightFrac: 0.5,
    lookFrac: 0.4,
    easing: 'cinematic',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.12,
    speed: 1,
    preferredAspects: ['16:9', '1:1', '9:16'],
    safe: { min: 10, max: 42, preferred: 18 },
    styleTags: ['orbit', '360', 'showcase'],
  }),
  t({
    id: 'circle_around',
    label: 'Circle Around Character',
    description: 'Tight stylish circle',
    category: 'orbit',
    motion: 'orbit',
    durationScale: 1,
    baseFov: 36,
    radiusMul: 0.95,
    heightFrac: 0.58,
    lookFrac: 0.55,
    easing: 'hermite',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.28,
    speed: 1.05,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 24, preferred: 11 },
    styleTags: ['orbit', 'tight', 'face'],
  }),
  t({
    id: 'spiral_camera',
    label: 'Spiral Camera',
    description: 'Rising spiral around subject',
    category: 'orbit',
    motion: 'spiral',
    durationScale: 1.1,
    baseFov: 44,
    radiusMul: 1.1,
    heightFrac: 0.25,
    lookFrac: 0.4,
    easing: 'cinematic',
    framing: 'keep_character',
    followTarget: 'chest',
    dofStrength: 0.14,
    speed: 1,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 8, max: 34, preferred: 15 },
    styleTags: ['spiral', 'crane', 'dramatic'],
  }),
  t({
    id: 'hero_entrance',
    label: 'Hero Entrance',
    description: 'Low push-in as the hero arrives',
    category: 'hero',
    motion: 'entrance',
    durationScale: 0.9,
    baseFov: 34,
    endFov: 30,
    radiusMul: 1.3,
    heightFrac: 0.15,
    lookFrac: 0.62,
    easing: 'easeOut',
    framing: 'keep_face',
    followTarget: 'chest',
    dofStrength: 0.22,
    speed: 1.1,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 7, max: 32, preferred: 14 },
    styleTags: ['hero', 'entrance', 'low'],
  }),
  t({
    id: 'hero_reveal',
    label: 'Hero Reveal',
    description: 'Pull back to reveal the full hero',
    category: 'hero',
    motion: 'reveal',
    durationScale: 1,
    baseFov: 32,
    endFov: 44,
    radiusMul: 0.7,
    heightFrac: 0.55,
    lookFrac: 0.5,
    easing: 'easeInOut',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.2,
    speed: 0.9,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 36, preferred: 12 },
    styleTags: ['hero', 'reveal', 'pull'],
  }),
  t({
    id: 'low_angle_hero',
    label: 'Low Angle Hero',
    description: 'Powerful upward hero framing',
    category: 'angle',
    motion: 'low_hero',
    durationScale: 0.8,
    baseFov: 36,
    radiusMul: 1.0,
    heightFrac: 0.08,
    lookFrac: 0.7,
    easing: 'cinematic',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.25,
    speed: 0.85,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 26, preferred: 11 },
    styleTags: ['hero', 'low', 'dramatic'],
  }),
  t({
    id: 'high_angle_reveal',
    label: 'High Angle Reveal',
    description: 'Descending high-angle reveal',
    category: 'angle',
    motion: 'high_reveal',
    durationScale: 1,
    baseFov: 46,
    endFov: 40,
    radiusMul: 1.35,
    heightFrac: 1.15,
    lookFrac: 0.35,
    easing: 'easeIn',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.1,
    speed: 0.95,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 10, max: 40, preferred: 20 },
    styleTags: ['high', 'reveal', 'stage'],
  }),
  t({
    id: 'dance_performance',
    label: 'Dance Performance',
    description: 'Energetic dance coverage',
    category: 'performance',
    motion: 'dynamic_cuts',
    durationScale: 1,
    baseFov: 38,
    radiusMul: 0.95,
    heightFrac: 0.48,
    lookFrac: 0.45,
    easing: 'catmull',
    framing: 'dynamic',
    followTarget: 'chest',
    dofStrength: 0.12,
    speed: 1.25,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 28, preferred: 12 },
    styleTags: ['dance', 'energy', 'performance'],
  }),
  t({
    id: 'music_video',
    label: 'Music Video',
    description: 'MV-style cuts, arcs and close-ups',
    category: 'performance',
    motion: 'dynamic_cuts',
    durationScale: 1.05,
    baseFov: 34,
    radiusMul: 0.85,
    heightFrac: 0.6,
    lookFrac: 0.58,
    easing: 'bezier',
    framing: 'dynamic',
    followTarget: 'face',
    dofStrength: 0.35,
    speed: 1.15,
    preferredAspects: ['16:9', '9:16', '1:1'],
    safe: { min: 5, max: 26, preferred: 10 },
    styleTags: ['mv', 'cuts', 'close', 'music'],
  }),
  t({
    id: 'stage_performance',
    label: 'Stage Performance',
    description: 'Wide stage crane to performance',
    category: 'performance',
    motion: 'crane_up',
    durationScale: 1.1,
    baseFov: 48,
    radiusMul: 1.6,
    heightFrac: 0.7,
    lookFrac: 0.35,
    easing: 'cinematic',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.08,
    speed: 0.85,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 14, max: 50, preferred: 24 },
    styleTags: ['stage', 'wide', 'crane'],
  }),
  t({
    id: 'anime_intro',
    label: 'Anime Intro',
    description: 'Dramatic anime OP-style open',
    category: 'performance',
    motion: 'entrance',
    durationScale: 1,
    baseFov: 40,
    endFov: 34,
    radiusMul: 1.4,
    heightFrac: 0.4,
    lookFrac: 0.55,
    easing: 'cinematic',
    framing: 'auto_reframe',
    followTarget: 'chest',
    dofStrength: 0.2,
    speed: 1.05,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 8, max: 38, preferred: 16 },
    styleTags: ['anime', 'intro', 'dramatic'],
  }),
  t({
    id: 'anime_ending',
    label: 'Anime Ending',
    description: 'Soft ED pull-out and settle',
    category: 'performance',
    motion: 'pull_out',
    durationScale: 1.15,
    baseFov: 36,
    endFov: 46,
    radiusMul: 0.9,
    heightFrac: 0.55,
    lookFrac: 0.5,
    easing: 'easeIn',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.22,
    speed: 0.7,
    preferredAspects: ['16:9'],
    safe: { min: 8, max: 40, preferred: 14 },
    styleTags: ['anime', 'ending', 'soft', 'pull'],
  }),
  t({
    id: 'tiktok_vertical',
    label: 'TikTok Vertical',
    description: 'Punchy 9:16 social framing',
    category: 'social',
    motion: 'push_in',
    durationScale: 0.75,
    baseFov: 42,
    endFov: 34,
    radiusMul: 0.9,
    heightFrac: 0.55,
    lookFrac: 0.55,
    easing: 'easeOut',
    framing: 'keep_full_body',
    followTarget: 'chest',
    dofStrength: 0.15,
    speed: 1.2,
    preferredAspects: ['9:16'],
    safe: { min: 8, max: 28, preferred: 13 },
    styleTags: ['social', 'vertical', 'tiktok', 'fast'],
  }),
  t({
    id: 'youtube_shorts',
    label: 'YouTube Shorts',
    description: 'Clean vertical showcase',
    category: 'social',
    motion: 'orbit',
    durationScale: 0.9,
    baseFov: 40,
    radiusMul: 1.05,
    heightFrac: 0.5,
    lookFrac: 0.48,
    easing: 'cinematic',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.12,
    speed: 1,
    preferredAspects: ['9:16'],
    safe: { min: 9, max: 30, preferred: 14 },
    styleTags: ['social', 'vertical', 'shorts', 'showcase'],
  }),
  t({
    id: 'instagram_reel',
    label: 'Instagram Reel',
    description: 'Stylish vertical reel motion',
    category: 'social',
    motion: 'arc',
    durationScale: 0.8,
    baseFov: 38,
    radiusMul: 0.95,
    heightFrac: 0.58,
    lookFrac: 0.55,
    easing: 'hermite',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.3,
    speed: 1.15,
    preferredAspects: ['9:16', '4:5'],
    safe: { min: 6, max: 24, preferred: 11 },
    styleTags: ['social', 'vertical', 'reel', 'style'],
  }),
  t({
    id: 'action_scene',
    label: 'Action Scene',
    description: 'Dynamic action coverage',
    category: 'action',
    motion: 'dynamic_cuts',
    durationScale: 0.95,
    baseFov: 40,
    radiusMul: 1.0,
    heightFrac: 0.4,
    lookFrac: 0.45,
    easing: 'catmull',
    framing: 'dynamic',
    followTarget: 'chest',
    dofStrength: 0.1,
    speed: 1.4,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 6, max: 30, preferred: 12 },
    styleTags: ['action', 'fast', 'dynamic'],
  }),
  t({
    id: 'combat_camera',
    label: 'Combat Camera',
    description: 'Fight-scene angles and whip pans',
    category: 'action',
    motion: 'dynamic_cuts',
    durationScale: 0.9,
    baseFov: 38,
    radiusMul: 0.9,
    heightFrac: 0.35,
    lookFrac: 0.5,
    easing: 'bezier',
    framing: 'dynamic',
    followTarget: 'chest',
    dofStrength: 0.08,
    speed: 1.45,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 5, max: 26, preferred: 10 },
    styleTags: ['combat', 'action', 'fast'],
  }),
  t({
    id: 'boss_introduction',
    label: 'Boss Introduction',
    description: 'Dramatic low-to-high boss reveal',
    category: 'action',
    motion: 'high_reveal',
    durationScale: 1.05,
    baseFov: 34,
    endFov: 48,
    radiusMul: 1.2,
    heightFrac: 0.1,
    lookFrac: 0.55,
    easing: 'cinematic',
    framing: 'keep_character',
    followTarget: 'full',
    dofStrength: 0.18,
    speed: 0.9,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 8, max: 40, preferred: 16 },
    styleTags: ['boss', 'reveal', 'dramatic'],
  }),
  t({
    id: 'dynamic_action',
    label: 'Dynamic Action Camera',
    description: 'Aggressive orbit + push',
    category: 'action',
    motion: 'orbit_fast',
    durationScale: 0.85,
    baseFov: 42,
    radiusMul: 0.85,
    heightFrac: 0.45,
    lookFrac: 0.5,
    easing: 'catmull',
    framing: 'dynamic',
    followTarget: 'chest',
    dofStrength: 0.1,
    speed: 1.5,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 5, max: 24, preferred: 9 },
    styleTags: ['action', 'orbit', 'fast'],
  }),
  t({
    id: 'dialogue_scene',
    label: 'Dialogue Scene',
    description: 'Soft medium framing for talk',
    category: 'dialogue',
    motion: 'static_hold',
    durationScale: 0.9,
    baseFov: 36,
    radiusMul: 0.75,
    heightFrac: 0.62,
    lookFrac: 0.62,
    easing: 'easeInOut',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.4,
    speed: 0.65,
    preferredAspects: ['16:9', '1:1'],
    safe: { min: 5, max: 18, preferred: 8 },
    styleTags: ['dialogue', 'soft', 'face'],
  }),
  t({
    id: 'over_shoulder',
    label: 'Over Shoulder',
    description: 'OTS conversation framing',
    category: 'dialogue',
    motion: 'ots',
    durationScale: 0.8,
    baseFov: 34,
    radiusMul: 0.7,
    heightFrac: 0.65,
    lookFrac: 0.6,
    easing: 'cinematic',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.45,
    speed: 0.7,
    preferredAspects: ['16:9'],
    safe: { min: 4, max: 16, preferred: 7 },
    styleTags: ['dialogue', 'ots', 'face'],
  }),
  t({
    id: 'walking_follow',
    label: 'Walking Follow',
    description: 'Behind follow at walk pace',
    category: 'tracking',
    motion: 'follow_walk',
    durationScale: 1,
    baseFov: 40,
    radiusMul: 0.9,
    heightFrac: 0.55,
    lookFrac: 0.45,
    easing: 'cinematic',
    framing: 'keep_character',
    followTarget: 'root',
    dofStrength: 0.12,
    speed: 1,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 24, preferred: 11 },
    styleTags: ['follow', 'walk', 'track'],
  }),
  t({
    id: 'running_follow',
    label: 'Running Follow',
    description: 'Chase follow with urgency',
    category: 'tracking',
    motion: 'follow_run',
    durationScale: 0.85,
    baseFov: 42,
    radiusMul: 0.85,
    heightFrac: 0.5,
    lookFrac: 0.45,
    easing: 'easeOut',
    framing: 'dynamic',
    followTarget: 'root',
    dofStrength: 0.08,
    speed: 1.4,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 5, max: 22, preferred: 9 },
    styleTags: ['follow', 'run', 'fast'],
  }),
  t({
    id: 'side_tracking',
    label: 'Side Tracking',
    description: 'Lateral tracking shot',
    category: 'tracking',
    motion: 'track_side',
    durationScale: 1,
    baseFov: 40,
    radiusMul: 0.95,
    heightFrac: 0.5,
    lookFrac: 0.45,
    easing: 'hermite',
    framing: 'keep_character',
    followTarget: 'chest',
    dofStrength: 0.12,
    speed: 1.05,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 6, max: 26, preferred: 12 },
    styleTags: ['track', 'side'],
  }),
  t({
    id: 'front_tracking',
    label: 'Front Tracking',
    description: 'Lead camera walking backward',
    category: 'tracking',
    motion: 'track_front',
    durationScale: 1,
    baseFov: 38,
    radiusMul: 1.0,
    heightFrac: 0.55,
    lookFrac: 0.5,
    easing: 'cinematic',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.18,
    speed: 1,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 24, preferred: 12 },
    styleTags: ['track', 'front'],
  }),
  t({
    id: 'back_tracking',
    label: 'Back Tracking',
    description: 'Trailing camera from behind',
    category: 'tracking',
    motion: 'track_back',
    durationScale: 1,
    baseFov: 40,
    radiusMul: 0.95,
    heightFrac: 0.55,
    lookFrac: 0.4,
    easing: 'cinematic',
    framing: 'keep_character',
    followTarget: 'root',
    dofStrength: 0.12,
    speed: 1,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 24, preferred: 11 },
    styleTags: ['track', 'back'],
  }),
  t({
    id: 'close_up',
    label: 'Close Up',
    description: 'Intimate face framing',
    category: 'framing',
    motion: 'static_hold',
    durationScale: 0.7,
    baseFov: 28,
    radiusMul: 0.4,
    heightFrac: 0.78,
    lookFrac: 0.78,
    easing: 'cinematic',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.55,
    speed: 0.7,
    preferredAspects: ['16:9', '9:16', '1:1'],
    safe: { min: 3.5, max: 12, preferred: 5.5 },
    styleTags: ['close', 'face', 'dof'],
  }),
  t({
    id: 'extreme_close_up',
    label: 'Extreme Close Up',
    description: 'Eyes / detail intensity',
    category: 'framing',
    motion: 'push_in',
    durationScale: 0.65,
    baseFov: 26,
    endFov: 22,
    radiusMul: 0.28,
    heightFrac: 0.82,
    lookFrac: 0.82,
    easing: 'easeIn',
    framing: 'keep_eyes',
    followTarget: 'eyes',
    dofStrength: 0.7,
    speed: 0.75,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 2.8, max: 9, preferred: 4.2 },
    styleTags: ['ecu', 'eyes', 'dof'],
  }),
  t({
    id: 'medium_shot',
    label: 'Medium Shot',
    description: 'Waist-up classic framing',
    category: 'framing',
    motion: 'static_hold',
    durationScale: 0.75,
    baseFov: 36,
    radiusMul: 0.7,
    heightFrac: 0.55,
    lookFrac: 0.55,
    easing: 'easeInOut',
    framing: 'keep_character',
    followTarget: 'chest',
    dofStrength: 0.25,
    speed: 0.75,
    preferredAspects: ['16:9', '9:16', '4:5'],
    safe: { min: 5, max: 18, preferred: 9 },
    styleTags: ['medium', 'chest'],
  }),
  t({
    id: 'full_body_shot',
    label: 'Full Body Shot',
    description: 'Head-to-toe presentation',
    category: 'framing',
    motion: 'static_hold',
    durationScale: 0.8,
    baseFov: 42,
    radiusMul: 1.15,
    heightFrac: 0.45,
    lookFrac: 0.35,
    easing: 'cinematic',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.1,
    speed: 0.75,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 10, max: 36, preferred: 16 },
    styleTags: ['full', 'body'],
  }),
  t({
    id: 'crane_shot',
    label: 'Crane Shot',
    description: 'Rising crane to overview',
    category: 'crane',
    motion: 'crane_up',
    durationScale: 1.1,
    baseFov: 44,
    radiusMul: 1.2,
    heightFrac: 0.2,
    lookFrac: 0.4,
    easing: 'cinematic',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.1,
    speed: 0.9,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 10, max: 44, preferred: 18 },
    styleTags: ['crane', 'rise'],
  }),
  t({
    id: 'drone_shot',
    label: 'Drone Shot',
    description: 'High aerial arc',
    category: 'crane',
    motion: 'drone',
    durationScale: 1.15,
    baseFov: 50,
    radiusMul: 1.7,
    heightFrac: 1.3,
    lookFrac: 0.25,
    easing: 'catmull',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.05,
    speed: 0.95,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 16, max: 60, preferred: 28 },
    styleTags: ['drone', 'aerial', 'wide'],
  }),
  t({
    id: 'arc_shot',
    label: 'Arc Shot',
    description: 'Quarter-circle cinematic arc',
    category: 'move',
    motion: 'arc',
    durationScale: 1,
    baseFov: 38,
    radiusMul: 1.05,
    heightFrac: 0.52,
    lookFrac: 0.48,
    easing: 'hermite',
    framing: 'auto_reframe',
    followTarget: 'chest',
    dofStrength: 0.16,
    speed: 1,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 7, max: 28, preferred: 13 },
    styleTags: ['arc', 'orbit'],
  }),
  t({
    id: 'zoom_in',
    label: 'Zoom In',
    description: 'Optical-feel FOV tighten',
    category: 'move',
    motion: 'zoom_in',
    durationScale: 0.85,
    baseFov: 48,
    endFov: 28,
    radiusMul: 1.0,
    heightFrac: 0.55,
    lookFrac: 0.55,
    easing: 'easeIn',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.35,
    speed: 0.9,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 7, max: 24, preferred: 12 },
    styleTags: ['zoom', 'in', 'face'],
  }),
  t({
    id: 'zoom_out',
    label: 'Zoom Out',
    description: 'Widen FOV to reveal scene',
    category: 'move',
    motion: 'zoom_out',
    durationScale: 0.9,
    baseFov: 28,
    endFov: 50,
    radiusMul: 1.0,
    heightFrac: 0.55,
    lookFrac: 0.45,
    easing: 'easeOut',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.15,
    speed: 0.9,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 7, max: 30, preferred: 12 },
    styleTags: ['zoom', 'out', 'reveal'],
  }),
  t({
    id: 'push_in',
    label: 'Push In',
    description: 'Dolly push toward subject',
    category: 'move',
    motion: 'push_in',
    durationScale: 0.9,
    baseFov: 40,
    radiusMul: 1.35,
    heightFrac: 0.55,
    lookFrac: 0.55,
    easing: 'easeInOut',
    framing: 'keep_face',
    followTarget: 'face',
    dofStrength: 0.28,
    speed: 0.95,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 5, max: 30, preferred: 14 },
    styleTags: ['dolly', 'push', 'in'],
  }),
  t({
    id: 'pull_out',
    label: 'Pull Out',
    description: 'Dolly pull away',
    category: 'move',
    motion: 'pull_out',
    durationScale: 0.95,
    baseFov: 36,
    radiusMul: 0.7,
    heightFrac: 0.55,
    lookFrac: 0.45,
    easing: 'easeInOut',
    framing: 'keep_full_body',
    followTarget: 'full',
    dofStrength: 0.18,
    speed: 0.9,
    preferredAspects: ['16:9', '9:16'],
    safe: { min: 6, max: 36, preferred: 12 },
    styleTags: ['dolly', 'pull', 'out'],
  }),
  t({
    id: 'cinematic_pan',
    label: 'Cinematic Pan',
    description: 'Gentle yaw pan across subject',
    category: 'move',
    motion: 'pan',
    durationScale: 0.95,
    baseFov: 40,
    radiusMul: 1.1,
    heightFrac: 0.5,
    lookFrac: 0.45,
    easing: 'cinematic',
    framing: 'auto_reframe',
    followTarget: 'chest',
    dofStrength: 0.14,
    speed: 0.85,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 8, max: 30, preferred: 15 },
    styleTags: ['pan', 'slow'],
  }),
  t({
    id: 'smooth_dolly',
    label: 'Smooth Dolly',
    description: 'Linear dolly with cinematic ease',
    category: 'move',
    motion: 'dolly',
    durationScale: 1,
    baseFov: 38,
    radiusMul: 1.2,
    heightFrac: 0.5,
    lookFrac: 0.48,
    easing: 'hermite',
    framing: 'keep_character',
    followTarget: 'chest',
    dofStrength: 0.16,
    speed: 0.9,
    preferredAspects: ['16:9', '21:9'],
    safe: { min: 8, max: 32, preferred: 15 },
    styleTags: ['dolly', 'smooth'],
  }),
];

export function getBuiltinTemplate(id: string): CameraTemplateDef | undefined {
  return BUILTIN_CAMERA_TEMPLATES.find((x) => x.id === id);
}

export const TEMPLATE_CATEGORY_LABELS: Record<string, string> = {
  showcase: 'Showcase',
  orbit: 'Orbit',
  hero: 'Hero',
  performance: 'Performance',
  social: 'Social / Vertical',
  action: 'Action',
  dialogue: 'Dialogue',
  tracking: 'Tracking',
  angle: 'Angles',
  framing: 'Framing',
  crane: 'Crane / Aerial',
  move: 'Camera Moves',
  user: 'My Templates',
};
